version: '3.8'

services:
  # data base
  db:
    container_name: jvault_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: Gabi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jvault
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  # visual interface for the database
  pgadmin:
    container_name: jvault_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jvault.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: